// Generado desde datos/Circulares.xlsx con herramientas/circulares.py. No editar a mano.
window.CIRCULARES = [
 {
  "c": "2026-001",
  "tipo": "Colocación",
  "nombre": "Formulador del año Epithelium",
  "grupo": "Terminados",
  "dirigida": "Médicos participantes en Protocolo Médico",
  "producto": "[PT0003] Revival Crema x 50 g",
  "ini": "2026-02-01",
  "fin": "2026-12-31",
  "objetivo": "Reconocer al médico que más Revival formule al cierre de 2026",
  "resumen": "Concurso para médicos de Protocolo Médico: quien más formule Revival en 2026 gana patrocinio económico para el Congreso Nacional de Dermatología 2026. Se presenta Revival cada mes en la visita y el médico entrega su reporte de ventas en los tiempos de la circular.",
  "obs": "",
  "pdf": "",
  "productos": [
   {
    "c": "PT0003",
    "n": "Revival Crema x 50 g"
   }
  ],
  "canales": [
   "20",
   "21",
   "22"
  ],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-002",
  "tipo": "Concurso colocación",
  "nombre": "¡Con Capilplus Acondicionador, ganas!",
  "grupo": "Producto terminado",
  "dirigida": "Equipo Visita Médica y Comercial",
  "producto": "[PT0014] Capilplus Acondicionador",
  "ini": "2026-01-01",
  "fin": "2026-06-30",
  "objetivo": "Dar a conocer Capilplus Acondicionador y colocar mínimo 300 unidades en el semestre",
  "resumen": "Concurso de la fuerza de ventas: incentivo por unidades colocadas de Capilplus Acondicionador. Zona Norte/Sur: 60, 70 u 80 uds = $150.000, $300.000 o $500.000; Clientes Especiales: 20, 30 o 40 uds. Los bonificados no suman. Liquidación en julio de 2026.",
  "obs": "",
  "pdf": "",
  "productos": [
   {
    "c": "PT0014",
    "n": "Capilplus Acondicionador"
   }
  ],
  "canales": [],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": true
 },
 {
  "c": "2026-003",
  "tipo": "Codificación y colocación",
  "nombre": "¡Capilplus Acondicionador el bonificado perfecto!",
  "grupo": "Producto terminado",
  "dirigida": "Canales 90, 10, 11, 50, 51, 61, 70 (no aplica Bella Piel)",
  "producto": "[PT0014] Capilplus Acondicionador",
  "ini": "2026-02-09",
  "fin": "2026-06-30",
  "objetivo": "Que los canales codifiquen Capilplus Acondicionador y evacuar mínimo 120 unidades",
  "resumen": "Por cada 6 unidades de Capilplus Cuidado Capilar o Capilplus DS, el cliente recibe 1 Capilplus Acondicionador bonificado. No aplica para Bella Piel (la coordinadora lo retira manualmente). Los bonificados no suman en las unidades vendidas.",
  "obs": "",
  "pdf": "",
  "productos": [
   {
    "c": "PT0014",
    "n": "Capilplus Acondicionador"
   }
  ],
  "canales": [
   "10",
   "11",
   "50",
   "51",
   "61",
   "70",
   "90"
  ],
  "clientes": [],
  "excluidos": [
   "Bella Piel S.A.S.",
   "Bella Piel S.A.S., Bella Piel Acomedica (AM)",
   "Bella Piel S.A.S., Bella Piel Bodega Distribucion (BDP)",
   "Bella Piel S.A.S., Bella Piel C.C Avenida Chile (AC)",
   "Bella Piel S.A.S., Bella Piel C.C Babilla Plaza (CB)",
   "Bella Piel S.A.S., Bella Piel C.C Buenavista (MN)",
   "Bella Piel S.A.S., Bella Piel C.C Caribe Plaza (CP)",
   "Bella Piel S.A.S., Bella Piel C.C Cañaveral (BC)",
   "Bella Piel S.A.S., Bella Piel C.C Cañaveral (BV)",
   "Bella Piel S.A.S., Bella Piel C.C Cedritos (CD)",
   "Bella Piel S.A.S., Bella Piel C.C Centro Suba (SU)",
   "Bella Piel S.A.S., Bella Piel C.C City Medica (MX)",
   "Bella Piel S.A.S., Bella Piel C.C Gran Plaza San Antonio (GT)",
   "Bella Piel S.A.S., Bella Piel C.C Gran Plaza Soacha (PG)",
   "Bella Piel S.A.S., Bella Piel C.C Gran Plaza el Sol (BS)",
   "Bella Piel S.A.S., Bella Piel C.C Granada Meta (ZG)",
   "Bella Piel S.A.S., Bella Piel C.C Jardin Plaza (JC)",
   "Bella Piel S.A.S., Bella Piel C.C La Casona Ph (CZ)",
   "Bella Piel S.A.S., Bella Piel C.C Los Caobos (LC)",
   "Bella Piel S.A.S., Bella Piel C.C Metropolis (ME)",
   "Bella Piel S.A.S., Bella Piel C.C Plaza Claro (PO)",
   "Bella Piel S.A.S., Bella Piel C.C Plaza Imperial 133 (IP)",
   "Bella Piel S.A.S., Bella Piel C.C Plaza de las Americas (AP)",
   "Bella Piel S.A.S., Bella Piel C.C Puerta del Norte (MH)",
   "Bella Piel S.A.S., Bella Piel C.C Salitre Plaza (PS)",
   "Bella Piel S.A.S., Bella Piel C.C San Diego 1485 (SD)",
   "Bella Piel S.A.S., Bella Piel C.C San Nicolas (MQ)",
   "Bella Piel S.A.S., Bella Piel C.C Santa Barbara (HB)",
   "Bella Piel S.A.S., Bella Piel C.C Santa Fe (SV)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Armenia (UA)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Cali 447 (UC)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Neiva (UN)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Pasto (PU)",
   "Bella Piel S.A.S., Bella Piel C.C Ventura Cucuta (VC)",
   "Bella Piel S.A.S., Bella Piel C.C Viva Wajira (VG)",
   "Bella Piel S.A.S., Bella Piel C.C Viva la Ceja (AL)",
   "Bella Piel S.A.S., Bella Piel C.C. Andino (AN)",
   "Bella Piel S.A.S., Bella Piel C.C. Arkadia (MA)",
   "Bella Piel S.A.S., Bella Piel C.C. Avenida (AF)",
   "Bella Piel S.A.S., Bella Piel C.C. Buenavista (BU)",
   "Bella Piel S.A.S., Bella Piel C.C. Cafam Floresta (CF)",
   "Bella Piel S.A.S., Bella Piel C.C. Calima (CC)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Chia (CH)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Logistico (PW)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Mayor (CM)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Mayor (CN)",
   "Bella Piel S.A.S., Bella Piel C.C. Chipichape (CA)",
   "Bella Piel S.A.S., Bella Piel C.C. Cosmocentro (CO)",
   "Bella Piel S.A.S., Bella Piel C.C. Diver Plaza (DP)",
   "Bella Piel S.A.S., Bella Piel C.C. Ecoplaza (EC)",
   "Bella Piel S.A.S., Bella Piel C.C. Edificio Torre Palatino (EP)",
   "Bella Piel S.A.S., Bella Piel C.C. El Tesoro Parque Comercial (MT)",
   "Bella Piel S.A.S., Bella Piel C.C. Florida Parque Comercial (ML)",
   "Bella Piel S.A.S., Bella Piel C.C. Fontanar (FT)",
   "Bella Piel S.A.S., Bella Piel C.C. Fundadores (FM)",
   "Bella Piel S.A.S., Bella Piel C.C. Galerias (GA)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Estacion (GE)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Estacion (GN)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Plaza - La Libertad (FP)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Plaza Alcaravan (AY)",
   "Bella Piel S.A.S., Bella Piel C.C. Guatapuri (UV)",
   "Bella Piel S.A.S., Bella Piel C.C. Hacienda Santa Barbara (HN)",
   "Bella Piel S.A.S., Bella Piel C.C. Hacienda Santa Barbara (HS)",
   "Bella Piel S.A.S., Bella Piel C.C. Hayuelos (HY)",
   "Bella Piel S.A.S., Bella Piel C.C. Holguines Trade Center (CG)",
   "Bella Piel S.A.S., Bella Piel C.C. Innovo Plaza (DI)",
   "Bella Piel S.A.S., Bella Piel C.C. Jardin Plaza (CJ)",
   "Bella Piel S.A.S., Bella Piel C.C. La Estacion (EI)",
   "Bella Piel S.A.S., Bella Piel C.C. La Estacion (LI)",
   "Bella Piel S.A.S., Bella Piel C.C. La Mansion (BB)",
   "Bella Piel S.A.S., Bella Piel C.C. Mall Plaza (BM)",
   "Bella Piel S.A.S., Bella Piel C.C. Mall Plaza Buenavista (BA)",
   "Bella Piel S.A.S., Bella Piel C.C. Mayorca (MY)",
   "Bella Piel S.A.S., Bella Piel C.C. Mercurio (MB)",
   "Bella Piel S.A.S., Bella Piel C.C. Molinos (MM)",
   "Bella Piel S.A.S., Bella Piel C.C. Multicentro Ibague (MI)",
   "Bella Piel S.A.S., Bella Piel C.C. Multiplaza (MF)",
   "Bella Piel S.A.S., Bella Piel C.C. Nuestro Bogota (NB)",
   "Bella Piel S.A.S., Bella Piel C.C. Nuestro Cartago (NC)",
   "Bella Piel S.A.S., Bella Piel C.C. Palatino (PL)",
   "Bella Piel S.A.S., Bella Piel C.C. Parque Alegra (BL)",
   "Bella Piel S.A.S., Bella Piel C.C. Parque la Colina (CE)",
   "Bella Piel S.A.S., Bella Piel C.C. Paseo Villa del Rio (PR)",
   "Bella Piel S.A.S., Bella Piel C.C. Pereira Plaza (PP)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza Central (PC)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza De Las Americas (PZ)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza Imperial (PI)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza Mayor (BP)",
   "Bella Piel S.A.S., Bella Piel C.C. Portal 80 (PN)",
   "Bella Piel S.A.S., Bella Piel C.C. Portal Quindio (PQ)",
   "Bella Piel S.A.S., Bella Piel C.C. Premium Plaza (MP)",
   "Bella Piel S.A.S., Bella Piel C.C. Primavera Urbana (VP)",
   "Bella Piel S.A.S., Bella Piel C.C. Salitre Plaza (SA)",
   "Bella Piel S.A.S., Bella Piel C.C. San Diego (MD)",
   "Bella Piel S.A.S., Bella Piel C.C. San Pedro (NS)",
   "Bella Piel S.A.S., Bella Piel C.C. Santa Fe (SN)",
   "Bella Piel S.A.S., Bella Piel C.C. Santa Fe Jumbo (SP)",
   "Bella Piel S.A.S., Bella Piel C.C. Santa Lucia Plaza (BN)",
   "Bella Piel S.A.S., Bella Piel C.C. Santafe (MS)",
   "Bella Piel S.A.S., Bella Piel C.C. Suchiima (RS)",
   "Bella Piel S.A.S., Bella Piel C.C. Titan Plaza (TE)",
   "Bella Piel S.A.S., Bella Piel C.C. Titan Plaza (TN)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro (CU)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro (UE)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Girardot (UG)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Medellin (MU)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Occidente (UO)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Primer Piso (UP)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Tunja (UT)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Villavicencio (VU)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Yopal (UY)",
   "Bella Piel S.A.S., Bella Piel C.C. Ventura Terreros (TB)",
   "Bella Piel S.A.S., Bella Piel C.C. Viva Barranquilla (BI)",
   "Bella Piel S.A.S., Bella Piel C.C. Viva Tunja (VT)",
   "Bella Piel S.A.S., Bella Piel C.C. Viva Villavicencio (VB)",
   "Bella Piel S.A.S., Bella Piel CC. La Quinta (BQ)",
   "Bella Piel S.A.S., Bella Piel Campanario (LC)",
   "Bella Piel S.A.S., Bella Piel Castellana 98 Isla (LL)",
   "Bella Piel S.A.S., Bella Piel Centro Especialista Cl 90 (CS)",
   "Bella Piel S.A.S., Bella Piel Centro Internacional de Especialistas (BE)",
   "Bella Piel S.A.S., Bella Piel Centro Mayor (CR)",
   "Bella Piel S.A.S., Bella Piel Centro Medico Calle 91 (NO)",
   "Bella Piel S.A.S., Bella Piel Centro Medico de la Sabana (SB)",
   "Bella Piel S.A.S., Bella Piel Clinica Porto Azul (BJ)",
   "Bella Piel S.A.S., Bella Piel Colina 153 Isla (IC)",
   "Bella Piel S.A.S., Bella Piel Edificio Castellana 98 (LL)",
   "Bella Piel S.A.S., Bella Piel Edificio Colon Corporacion Medico Empresarial PH- Las Nieves (CT)",
   "Bella Piel S.A.S., Bella Piel Edificio Global Medical Center (GM)",
   "Bella Piel S.A.S., Bella Piel Edificio North West 94 (NW)",
   "Bella Piel S.A.S., Bella Piel Edificio Salud y Servicios PH (MR)",
   "Bella Piel S.A.S., Bella Piel Edificio San Sebastián del Country (SS)",
   "Bella Piel S.A.S., Bella Piel Edificio Santa Ana Medical Center (SM)",
   "Bella Piel S.A.S., Bella Piel Edificio Torres Zentai (TZ)",
   "Bella Piel S.A.S., Bella Piel El Country (ZC)",
   "Bella Piel S.A.S., Bella Piel Florida Parque Comercial (LM)",
   "Bella Piel S.A.S., Bella Piel Gradeco Business Plaza (EG)",
   "Bella Piel S.A.S., Bella Piel Hayuelos (HA)",
   "Bella Piel S.A.S., Bella Piel Hospital Universitario La Fundacion Santafe De Bogota (FS)",
   "Bella Piel S.A.S., Bella Piel Llanogrande Plaza (VL)",
   "Bella Piel S.A.S., Bella Piel Mall Plaza Cartagena (CX)",
   "Bella Piel S.A.S., Bella Piel Mall Plaza Manizales (PM)",
   "Bella Piel S.A.S., Bella Piel Micentro Funza PH (FZ)",
   "Bella Piel S.A.S., Bella Piel North West Isla (NW)",
   "Bella Piel S.A.S., Bella Piel Pacific Center (CK)",
   "Bella Piel S.A.S., Bella Piel Palmetto Plaza 134 (TC)",
   "Bella Piel S.A.S., Bella Piel Parque Comercial Guacarí Sincelejo (GS)",
   "Bella Piel S.A.S., Bella Piel Pasaje Astoria (MJ)",
   "Bella Piel S.A.S., Bella Piel Proyecto de Vida Centro Profesional PH (CV)",
   "Bella Piel S.A.S., Bella Piel S.A.S C.C Gran Estacion (GO)",
   "Bella Piel S.A.S., Bella Piel S.A.S C.C Mayorca (YM)",
   "Bella Piel S.A.S., Bella Piel S.A.S C.C Palatino (LP)",
   "Bella Piel S.A.S., Bella Piel S.A.S Centro Comercial Plaza Imperial(PE)",
   "Bella Piel S.A.S., Bella Piel S.A.S., Centro Logistico (DM)",
   "Bella Piel S.A.S., Bella Piel Sabana Park Health & Businees (SH)",
   "Bella Piel S.A.S., Bella Piel Salud Vegas Torre Medica PH (MV)",
   "Bella Piel S.A.S., Bella Piel San Nicolas 2369 (MW)",
   "Bella Piel S.A.S., Bella Piel Supercentro Tulua la 14 (TS)",
   "Bella Piel S.A.S., Bella Piel Zonata Centro Medico (ZO)",
   "Tienda Dermocosmetica Bella Piel, Juanita Ceron Delgado"
  ],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-004",
  "tipo": "Codificación y evacuación",
  "nombre": "Gana más con la Parrilla Promocional",
  "grupo": "Producto Terminado",
  "dirigida": "Canales 20, 21, 22 (Protocolo Médico)",
  "producto": "[PT0003] Revival; [PT0012] Sensibath",
  "ini": "2026-02-01",
  "fin": "2026-03-31",
  "objetivo": "Presentar Revival y Sensibath a los médicos para promover su formulación",
  "resumen": "Parrilla de febrero-marzo en Protocolo Médico: el médico gana $8.000 por unidad de Revival y $3.000 por unidad de Sensibath evacuada y reportada. En estos productos se suspende el 5% habitual del programa durante la actividad.",
  "obs": "",
  "pdf": "",
  "productos": [
   {
    "c": "PT0003",
    "n": "Revival"
   },
   {
    "c": "PT0012",
    "n": "Sensibath"
   }
  ],
  "canales": [
   "20",
   "21",
   "22"
  ],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-005",
  "tipo": "Colocación",
  "nombre": "Concurso de ventas - Coordinador gana doble",
  "grupo": "Producto terminado",
  "dirigida": "Coordinadora de Ventas",
  "producto": "[PT0014] Capilplus Acondicionador",
  "ini": "2026-01-01",
  "fin": "2026-06-30",
  "objetivo": "Incentivar a ventas: la coordinadora gana el 50% de lo que gane su equipo",
  "resumen": "Complementa el concurso de Capilplus Acondicionador (circular 2026-002): la Coordinadora de Ventas recibe adicional el 50% de los premios de Zona Norte y/o Sur. Se liquida en julio de 2026 con el informe de cierre del semestre.",
  "obs": "",
  "pdf": "",
  "productos": [
   {
    "c": "PT0014",
    "n": "Capilplus Acondicionador"
   }
  ],
  "canales": [],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": true
 },
 {
  "c": "2026-006",
  "tipo": "Colocación",
  "nombre": "Combo Corporal Face & Body + Gel Anticelulitis",
  "grupo": "Magistral de Pedido",
  "dirigida": "Todos",
  "producto": "[MP0821] Face & Body; [MP0856] Gel Anticelulitis",
  "ini": "2026-02-01",
  "fin": "2026-03-31",
  "objetivo": "Evacuar 14 unidades de Gel Anticelulitis y rotar Crema Face & Body al cierre de marzo",
  "resumen": "Venta cruzada: por la compra de 2 unidades de Crema Hidratante Face & Body x 250 g [MP0821], el cliente recibe gratis 1 Gel Anticelulitis x 250 g [MP0856]. Aplica a todos los canales para magistral de pedido.",
  "obs": "",
  "pdf": "",
  "productos": [
   {
    "c": "MP0821",
    "n": "Face & Body"
   },
   {
    "c": "MP0856",
    "n": "Gel Anticelulitis"
   }
  ],
  "canales": [],
  "clientes": [],
  "excluidos": [],
  "todos": true,
  "interna": false
 },
 {
  "c": "2026-007",
  "tipo": "Informativa",
  "nombre": "Parrilla Productos Terminados 2026",
  "grupo": "Producto terminado",
  "dirigida": "Fuerza de Ventas",
  "producto": "Todos los productos terminados",
  "ini": "2026-01-01",
  "fin": "2026-12-31",
  "objetivo": "Presentar a ventas el cronograma anual de producto terminado y su parrilla promocional",
  "resumen": "Informa a la fuerza de ventas el cronograma anual de la parrilla promocional de producto terminado. Mercadeo entrega mes a mes la información de cada producto para generar recordación en los médicos y mayor ganancia en Protocolo Médico.",
  "obs": "",
  "pdf": "",
  "productos": [],
  "canales": [],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": true
 },
 {
  "c": "2026-008",
  "tipo": "Evacuación",
  "nombre": "Parrilla Promocional. Febrero, Marzo",
  "grupo": "Magistral de Pedido / Producto Terminado",
  "dirigida": "Canales 20, 21, 22",
  "producto": "[PT0014], [MP0137], [MP0534], [MP0821], [PT0003]",
  "ini": "2026-02-01",
  "fin": "2026-03-31",
  "objetivo": "Presentar la parrilla promocional al 100% del panel médico, con 1 impacto mensual",
  "resumen": "Parrilla febrero-marzo para canales 20, 21 y 22: Capilplus Acondicionador, Mentafort, Diclofenaco+Nicotinamida, Face & Body y Revival. Visita mensual (presencial en Bogotá, virtual en regiones), refuerzo semanal y mensaje unificado.",
  "obs": "",
  "pdf": "",
  "productos": [
   {
    "c": "PT0014",
    "n": ""
   },
   {
    "c": "MP0137",
    "n": ""
   },
   {
    "c": "MP0534",
    "n": ""
   },
   {
    "c": "MP0821",
    "n": ""
   },
   {
    "c": "PT0003",
    "n": ""
   }
  ],
  "canales": [
   "20",
   "21",
   "22"
  ],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-009",
  "tipo": "Evacuación",
  "nombre": "Parrilla Promocional. Abril - Junio",
  "grupo": "Magistral de Pedido / Producto Terminado",
  "dirigida": "Canales 20, 21, 22",
  "producto": "[PT0014], [PT0003], [PT0004], [MP0676], [MP0738], [MP0570]",
  "ini": "2026-04-01",
  "fin": "2026-06-30",
  "objetivo": "Presentar la parrilla promocional al 100% del panel médico, con 1 impacto mensual",
  "resumen": "Parrilla abril-junio para canales 20, 21 y 22: Capilplus Acondicionador, Revival, Hydrafort, Despigmentante Íntimo, Loción Tónica y Cobiolift. Visita mensual (presencial en Bogotá, virtual en regiones), refuerzo semanal y argumentación unificada.",
  "obs": "Prorrogada un mes por la circular 2026-019",
  "pdf": "",
  "productos": [
   {
    "c": "PT0014",
    "n": ""
   },
   {
    "c": "PT0003",
    "n": ""
   },
   {
    "c": "PT0004",
    "n": ""
   },
   {
    "c": "MP0676",
    "n": ""
   },
   {
    "c": "MP0738",
    "n": ""
   },
   {
    "c": "MP0570",
    "n": ""
   }
  ],
  "canales": [
   "20",
   "21",
   "22"
  ],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-010",
  "tipo": "Apoyo comercial",
  "nombre": "Apoyo comercial - Boston",
  "grupo": "Magistrales de pedido",
  "dirigida": "Boston Medical Group de Colombia S.A.S.",
  "producto": "[MP0473] Anestésico Boston Crema x 30 g",
  "ini": "2026-01-01",
  "fin": "2026-12-31",
  "objetivo": "Consolidar la relación con Boston Medical Group e incrementar sus compras de Anestésico Boston",
  "resumen": "Apoyo comercial a Boston Medical Group: por cada 120 unidades de [MP0473] Anestésico Boston Crema x 30 g se bonifican 24 unidades adicionales en el mismo pedido. Se calcula automáticamente en Odoo en cada orden de compra.",
  "obs": "",
  "pdf": "",
  "productos": [
   {
    "c": "MP0473",
    "n": "Anestésico Boston Crema x 30 g"
   }
  ],
  "canales": [],
  "clientes": [
   "Boston Medical Group de Colombia S.A.S."
  ],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-011",
  "tipo": "Colocación",
  "nombre": "Logra una piel perfecta en vacaciones",
  "grupo": "Producto terminado",
  "dirigida": "Canales 90, 10, 11, 13, 20, 21, 70",
  "producto": "[PT0003] Revival Crema x 50 g",
  "ini": "2026-05-11",
  "fin": "2026-07-30",
  "objetivo": "Colocar mínimo 200 unidades de Revival como obsequio por compras de Sunskin",
  "resumen": "Cliente: lleva 1 Revival gratis por cada 10 protectores Sunskin (emulsión, Oil Free o gel). Médico (clasificaciones 20-21): formulando 10 unidades de Sunskin recibe 1 Revival gratis. El bonificado no suma para el pedido.",
  "obs": "",
  "pdf": "",
  "productos": [
   {
    "c": "PT0003",
    "n": "Revival Crema x 50 g"
   }
  ],
  "canales": [
   "10",
   "11",
   "13",
   "20",
   "21",
   "70",
   "90"
  ],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-012",
  "tipo": "Evacuación",
  "nombre": "Aniversario Bella Piel - producto terminado Epithelium",
  "grupo": "Magistral de Pedido / Producto Terminado",
  "dirigida": "Bella Piel",
  "producto": "Producto Terminado",
  "ini": "2026-05-01",
  "fin": "2026-05-30",
  "objetivo": "Apoyar a Bella Piel en sus días de descuento de aniversario y generar rotación",
  "resumen": "6 días de descuento del 25% sobre el costo de venta antes de IVA, en las fechas que defina Bella Piel en mayo. El cliente envía las ventas POS al cierre y Epithelium liquida con Nota Crédito antes del 15 de junio de 2026.",
  "obs": "El PDF dice año 2025 en la fecha final; se asumió 2026",
  "pdf": "",
  "productos": [],
  "canales": [],
  "clientes": [
   "Bella Piel S.A.S.",
   "Bella Piel S.A.S., Bella Piel Acomedica (AM)",
   "Bella Piel S.A.S., Bella Piel Bodega Distribucion (BDP)",
   "Bella Piel S.A.S., Bella Piel C.C Avenida Chile (AC)",
   "Bella Piel S.A.S., Bella Piel C.C Babilla Plaza (CB)",
   "Bella Piel S.A.S., Bella Piel C.C Buenavista (MN)",
   "Bella Piel S.A.S., Bella Piel C.C Caribe Plaza (CP)",
   "Bella Piel S.A.S., Bella Piel C.C Cañaveral (BC)",
   "Bella Piel S.A.S., Bella Piel C.C Cañaveral (BV)",
   "Bella Piel S.A.S., Bella Piel C.C Cedritos (CD)",
   "Bella Piel S.A.S., Bella Piel C.C Centro Suba (SU)",
   "Bella Piel S.A.S., Bella Piel C.C City Medica (MX)",
   "Bella Piel S.A.S., Bella Piel C.C Gran Plaza San Antonio (GT)",
   "Bella Piel S.A.S., Bella Piel C.C Gran Plaza Soacha (PG)",
   "Bella Piel S.A.S., Bella Piel C.C Gran Plaza el Sol (BS)",
   "Bella Piel S.A.S., Bella Piel C.C Granada Meta (ZG)",
   "Bella Piel S.A.S., Bella Piel C.C Jardin Plaza (JC)",
   "Bella Piel S.A.S., Bella Piel C.C La Casona Ph (CZ)",
   "Bella Piel S.A.S., Bella Piel C.C Los Caobos (LC)",
   "Bella Piel S.A.S., Bella Piel C.C Metropolis (ME)",
   "Bella Piel S.A.S., Bella Piel C.C Plaza Claro (PO)",
   "Bella Piel S.A.S., Bella Piel C.C Plaza Imperial 133 (IP)",
   "Bella Piel S.A.S., Bella Piel C.C Plaza de las Americas (AP)",
   "Bella Piel S.A.S., Bella Piel C.C Puerta del Norte (MH)",
   "Bella Piel S.A.S., Bella Piel C.C Salitre Plaza (PS)",
   "Bella Piel S.A.S., Bella Piel C.C San Diego 1485 (SD)",
   "Bella Piel S.A.S., Bella Piel C.C San Nicolas (MQ)",
   "Bella Piel S.A.S., Bella Piel C.C Santa Barbara (HB)",
   "Bella Piel S.A.S., Bella Piel C.C Santa Fe (SV)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Armenia (UA)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Cali 447 (UC)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Neiva (UN)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Pasto (PU)",
   "Bella Piel S.A.S., Bella Piel C.C Ventura Cucuta (VC)",
   "Bella Piel S.A.S., Bella Piel C.C Viva Wajira (VG)",
   "Bella Piel S.A.S., Bella Piel C.C Viva la Ceja (AL)",
   "Bella Piel S.A.S., Bella Piel C.C. Andino (AN)",
   "Bella Piel S.A.S., Bella Piel C.C. Arkadia (MA)",
   "Bella Piel S.A.S., Bella Piel C.C. Avenida (AF)",
   "Bella Piel S.A.S., Bella Piel C.C. Buenavista (BU)",
   "Bella Piel S.A.S., Bella Piel C.C. Cafam Floresta (CF)",
   "Bella Piel S.A.S., Bella Piel C.C. Calima (CC)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Chia (CH)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Logistico (PW)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Mayor (CM)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Mayor (CN)",
   "Bella Piel S.A.S., Bella Piel C.C. Chipichape (CA)",
   "Bella Piel S.A.S., Bella Piel C.C. Cosmocentro (CO)",
   "Bella Piel S.A.S., Bella Piel C.C. Diver Plaza (DP)",
   "Bella Piel S.A.S., Bella Piel C.C. Ecoplaza (EC)",
   "Bella Piel S.A.S., Bella Piel C.C. Edificio Torre Palatino (EP)",
   "Bella Piel S.A.S., Bella Piel C.C. El Tesoro Parque Comercial (MT)",
   "Bella Piel S.A.S., Bella Piel C.C. Florida Parque Comercial (ML)",
   "Bella Piel S.A.S., Bella Piel C.C. Fontanar (FT)",
   "Bella Piel S.A.S., Bella Piel C.C. Fundadores (FM)",
   "Bella Piel S.A.S., Bella Piel C.C. Galerias (GA)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Estacion (GE)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Estacion (GN)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Plaza - La Libertad (FP)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Plaza Alcaravan (AY)",
   "Bella Piel S.A.S., Bella Piel C.C. Guatapuri (UV)",
   "Bella Piel S.A.S., Bella Piel C.C. Hacienda Santa Barbara (HN)",
   "Bella Piel S.A.S., Bella Piel C.C. Hacienda Santa Barbara (HS)",
   "Bella Piel S.A.S., Bella Piel C.C. Hayuelos (HY)",
   "Bella Piel S.A.S., Bella Piel C.C. Holguines Trade Center (CG)",
   "Bella Piel S.A.S., Bella Piel C.C. Innovo Plaza (DI)",
   "Bella Piel S.A.S., Bella Piel C.C. Jardin Plaza (CJ)",
   "Bella Piel S.A.S., Bella Piel C.C. La Estacion (EI)",
   "Bella Piel S.A.S., Bella Piel C.C. La Estacion (LI)",
   "Bella Piel S.A.S., Bella Piel C.C. La Mansion (BB)",
   "Bella Piel S.A.S., Bella Piel C.C. Mall Plaza (BM)",
   "Bella Piel S.A.S., Bella Piel C.C. Mall Plaza Buenavista (BA)",
   "Bella Piel S.A.S., Bella Piel C.C. Mayorca (MY)",
   "Bella Piel S.A.S., Bella Piel C.C. Mercurio (MB)",
   "Bella Piel S.A.S., Bella Piel C.C. Molinos (MM)",
   "Bella Piel S.A.S., Bella Piel C.C. Multicentro Ibague (MI)",
   "Bella Piel S.A.S., Bella Piel C.C. Multiplaza (MF)",
   "Bella Piel S.A.S., Bella Piel C.C. Nuestro Bogota (NB)",
   "Bella Piel S.A.S., Bella Piel C.C. Nuestro Cartago (NC)",
   "Bella Piel S.A.S., Bella Piel C.C. Palatino (PL)",
   "Bella Piel S.A.S., Bella Piel C.C. Parque Alegra (BL)",
   "Bella Piel S.A.S., Bella Piel C.C. Parque la Colina (CE)",
   "Bella Piel S.A.S., Bella Piel C.C. Paseo Villa del Rio (PR)",
   "Bella Piel S.A.S., Bella Piel C.C. Pereira Plaza (PP)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza Central (PC)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza De Las Americas (PZ)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza Imperial (PI)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza Mayor (BP)",
   "Bella Piel S.A.S., Bella Piel C.C. Portal 80 (PN)",
   "Bella Piel S.A.S., Bella Piel C.C. Portal Quindio (PQ)",
   "Bella Piel S.A.S., Bella Piel C.C. Premium Plaza (MP)",
   "Bella Piel S.A.S., Bella Piel C.C. Primavera Urbana (VP)",
   "Bella Piel S.A.S., Bella Piel C.C. Salitre Plaza (SA)",
   "Bella Piel S.A.S., Bella Piel C.C. San Diego (MD)",
   "Bella Piel S.A.S., Bella Piel C.C. San Pedro (NS)",
   "Bella Piel S.A.S., Bella Piel C.C. Santa Fe (SN)",
   "Bella Piel S.A.S., Bella Piel C.C. Santa Fe Jumbo (SP)",
   "Bella Piel S.A.S., Bella Piel C.C. Santa Lucia Plaza (BN)",
   "Bella Piel S.A.S., Bella Piel C.C. Santafe (MS)",
   "Bella Piel S.A.S., Bella Piel C.C. Suchiima (RS)",
   "Bella Piel S.A.S., Bella Piel C.C. Titan Plaza (TE)",
   "Bella Piel S.A.S., Bella Piel C.C. Titan Plaza (TN)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro (CU)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro (UE)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Girardot (UG)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Medellin (MU)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Occidente (UO)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Primer Piso (UP)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Tunja (UT)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Villavicencio (VU)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Yopal (UY)",
   "Bella Piel S.A.S., Bella Piel C.C. Ventura Terreros (TB)",
   "Bella Piel S.A.S., Bella Piel C.C. Viva Barranquilla (BI)",
   "Bella Piel S.A.S., Bella Piel C.C. Viva Tunja (VT)",
   "Bella Piel S.A.S., Bella Piel C.C. Viva Villavicencio (VB)",
   "Bella Piel S.A.S., Bella Piel CC. La Quinta (BQ)",
   "Bella Piel S.A.S., Bella Piel Campanario (LC)",
   "Bella Piel S.A.S., Bella Piel Castellana 98 Isla (LL)",
   "Bella Piel S.A.S., Bella Piel Centro Especialista Cl 90 (CS)",
   "Bella Piel S.A.S., Bella Piel Centro Internacional de Especialistas (BE)",
   "Bella Piel S.A.S., Bella Piel Centro Mayor (CR)",
   "Bella Piel S.A.S., Bella Piel Centro Medico Calle 91 (NO)",
   "Bella Piel S.A.S., Bella Piel Centro Medico de la Sabana (SB)",
   "Bella Piel S.A.S., Bella Piel Clinica Porto Azul (BJ)",
   "Bella Piel S.A.S., Bella Piel Colina 153 Isla (IC)",
   "Bella Piel S.A.S., Bella Piel Edificio Castellana 98 (LL)",
   "Bella Piel S.A.S., Bella Piel Edificio Colon Corporacion Medico Empresarial PH- Las Nieves (CT)",
   "Bella Piel S.A.S., Bella Piel Edificio Global Medical Center (GM)",
   "Bella Piel S.A.S., Bella Piel Edificio North West 94 (NW)",
   "Bella Piel S.A.S., Bella Piel Edificio Salud y Servicios PH (MR)",
   "Bella Piel S.A.S., Bella Piel Edificio San Sebastián del Country (SS)",
   "Bella Piel S.A.S., Bella Piel Edificio Santa Ana Medical Center (SM)",
   "Bella Piel S.A.S., Bella Piel Edificio Torres Zentai (TZ)",
   "Bella Piel S.A.S., Bella Piel El Country (ZC)",
   "Bella Piel S.A.S., Bella Piel Florida Parque Comercial (LM)",
   "Bella Piel S.A.S., Bella Piel Gradeco Business Plaza (EG)",
   "Bella Piel S.A.S., Bella Piel Hayuelos (HA)",
   "Bella Piel S.A.S., Bella Piel Hospital Universitario La Fundacion Santafe De Bogota (FS)",
   "Bella Piel S.A.S., Bella Piel Llanogrande Plaza (VL)",
   "Bella Piel S.A.S., Bella Piel Mall Plaza Cartagena (CX)",
   "Bella Piel S.A.S., Bella Piel Mall Plaza Manizales (PM)",
   "Bella Piel S.A.S., Bella Piel Micentro Funza PH (FZ)",
   "Bella Piel S.A.S., Bella Piel North West Isla (NW)",
   "Bella Piel S.A.S., Bella Piel Pacific Center (CK)",
   "Bella Piel S.A.S., Bella Piel Palmetto Plaza 134 (TC)",
   "Bella Piel S.A.S., Bella Piel Parque Comercial Guacarí Sincelejo (GS)",
   "Bella Piel S.A.S., Bella Piel Pasaje Astoria (MJ)",
   "Bella Piel S.A.S., Bella Piel Proyecto de Vida Centro Profesional PH (CV)",
   "Bella Piel S.A.S., Bella Piel S.A.S C.C Gran Estacion (GO)",
   "Bella Piel S.A.S., Bella Piel S.A.S C.C Mayorca (YM)",
   "Bella Piel S.A.S., Bella Piel S.A.S C.C Palatino (LP)",
   "Bella Piel S.A.S., Bella Piel S.A.S Centro Comercial Plaza Imperial(PE)",
   "Bella Piel S.A.S., Bella Piel S.A.S., Centro Logistico (DM)",
   "Bella Piel S.A.S., Bella Piel Sabana Park Health & Businees (SH)",
   "Bella Piel S.A.S., Bella Piel Salud Vegas Torre Medica PH (MV)",
   "Bella Piel S.A.S., Bella Piel San Nicolas 2369 (MW)",
   "Bella Piel S.A.S., Bella Piel Supercentro Tulua la 14 (TS)",
   "Bella Piel S.A.S., Bella Piel Zonata Centro Medico (ZO)",
   "Tienda Dermocosmetica Bella Piel, Juanita Ceron Delgado"
  ],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-013",
  "tipo": "Concurso colocación",
  "nombre": "Soy un Influencer E!",
  "grupo": "Producto terminado",
  "dirigida": "Canal 80 (colaboradores)",
  "producto": "Todos los productos terminados",
  "ini": "2026-05-01",
  "fin": "2026-06-12",
  "objetivo": "Promover que los colaboradores creen contenido para Facebook e Instagram de Epithelium",
  "resumen": "Concurso individual para colaboradores de planta con un video corto (30 a 90 s) sobre productos o el laboratorio; mínimo 10 videos. El ganador recibe $150.000 y su video se publica. Inscripción del 6 al 12 de mayo; ganador el 9 de junio.",
  "obs": "",
  "pdf": "",
  "productos": [],
  "canales": [
   "80"
  ],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": true
 },
 {
  "c": "2026-014",
  "tipo": "Evacuación",
  "nombre": "Prepara tus Vacaciones con Dermatodo",
  "grupo": "Producto Terminado",
  "dirigida": "Dermatodo",
  "producto": "[PT0012] Sensibath; [PT0002] Capilplus DS; [PT0011] Capilplus Biotina",
  "ini": "2026-05-25",
  "fin": "2026-05-30",
  "objetivo": "Apoyar a Dermatodo en su campaña Prepara tus Vacaciones con Capilplus y Sensibath",
  "resumen": "6 días de descuento del 25% sobre el costo de venta antes de IVA, del 25 al 30 de mayo, en Sensibath, Capilplus DS y Capilplus Biotina. Dermatodo envía las ventas POS y se liquida con Nota Crédito entre el 9 y el 16 de junio de 2026.",
  "obs": "El PDF dice año 2025 en la fecha final; se asumió 2026",
  "pdf": "",
  "productos": [
   {
    "c": "PT0012",
    "n": "Sensibath"
   },
   {
    "c": "PT0002",
    "n": "Capilplus DS"
   },
   {
    "c": "PT0011",
    "n": "Capilplus Biotina"
   }
  ],
  "canales": [],
  "clientes": [
   "Ciruderma S.A.S., Dermatodo C.C. Avenida Chile",
   "Ciruderma S.A.S., Dermatodo C.C. Cedritos 151",
   "Ciruderma S.A.S., Dermatodo C.C. Centro 93",
   "Ciruderma S.A.S., Dermatodo C.C. Centro Chia",
   "Ciruderma S.A.S., Dermatodo C.C. Centro Mayor",
   "Ciruderma S.A.S., Dermatodo C.C. Gran Estacion",
   "Ciruderma S.A.S., Dermatodo C.C. Mall 138",
   "Ciruderma S.A.S., Dermatodo C.C. Metropolis",
   "Ciruderma S.A.S., Dermatodo C.C. Niza",
   "Ciruderma S.A.S., Dermatodo C.C. Sabana Norte",
   "Ciruderma S.A.S., Dermatodo C.C. Salitre Plaza",
   "Ciruderma S.A.S., Dermatodo C.C. Unicentro",
   "Ciruderma S.A.S., Dermatodo Calle 72",
   "Ciruderma S.A.S., Dermatodo Calle 92",
   "Ciruderma S.A.S., Dermatodo Centro Medico de la Sabana",
   "Ciruderma S.A.S., Dermatodo Colina",
   "Ciruderma S.A.S., Dermatodo Edificio el Bosque",
   "Ciruderma S.A.S., Dermatodo Santa Barbara"
  ],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-015",
  "tipo": "Colocación",
  "nombre": "Combo cruzado Epithelium",
  "grupo": "Magistral de Pedido",
  "dirigida": "Canales 10, 11, 13, 20, 21, 30, 31, 70, 90",
  "producto": "[MP0676] Despigmentante Íntimo; [MP0738] Loción Tónica",
  "ini": "2026-05-11",
  "fin": "2026-06-30",
  "objetivo": "Codificar 50 unidades por referencia y zona e impulsar Despigmentante Íntimo y Loción Tónica",
  "resumen": "Combo cruzado: por la compra de 12 unidades de Despigmentante Íntimo [MP0676] se otorgan sin costo 4 unidades de Loción Tónica Espuma [MP0738]. Se gestiona en Odoo con aprobación de Gerencia General.",
  "obs": "",
  "pdf": "",
  "productos": [
   {
    "c": "MP0676",
    "n": "Despigmentante Íntimo"
   },
   {
    "c": "MP0738",
    "n": "Loción Tónica"
   }
  ],
  "canales": [
   "10",
   "11",
   "13",
   "20",
   "21",
   "30",
   "31",
   "70",
   "90"
  ],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-016",
  "tipo": "Colocación",
  "nombre": "Bonificación especial por codificación",
  "grupo": "Magistral de Pedido",
  "dirigida": "Canales 10, 11, 13, 21, 30, 31, 50, 70, 20 y 90 (8+3)",
  "producto": "[MP0570] Cobiolift Epithelium Crema x 15 g",
  "ini": "2026-05-11",
  "fin": "2026-06-30",
  "objetivo": "Impulsar codificación y rotación de Cobiolift con bonificación 8+2 (8+3 en canales 20 y 90)",
  "resumen": "Bonificación 8+2 por compra de Cobiolift Epithelium Crema x 15 g; los canales 20 y 90 reciben 8+3. También aplica a clientes que ya lo tienen codificado. Se aplica en Odoo con aprobación de Gerencia General.",
  "obs": "",
  "pdf": "",
  "productos": [
   {
    "c": "MP0570",
    "n": "Cobiolift Epithelium Crema x 15 g"
   }
  ],
  "canales": [
   "10",
   "11",
   "13",
   "20",
   "21",
   "30",
   "31",
   "50",
   "70",
   "90"
  ],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-017",
  "tipo": "Codificación",
  "nombre": "Codificación línea estética (CMX S.A.S.)",
  "grupo": "Producto Terminado",
  "dirigida": "Línea Estética (C.M.X. S.A.S.)",
  "producto": "Producto Terminado",
  "ini": "2026-05-29",
  "fin": "2026-05-29",
  "objetivo": "Bonificación 12+3 y plazo de 90 días por codificar la línea de producto terminado",
  "resumen": "Solo para el primer pedido de CMX S.A.S. (Línea Estética), que busca codificar el 100% del producto terminado: bonificación 12+3 en cada referencia y plazo especial de 90 días. Vigencia de un solo día (29 de mayo).",
  "obs": "Vigencia de un solo día",
  "pdf": "",
  "productos": [],
  "canales": [],
  "clientes": [
   "CMX S.A.S, Linea Estetica Centro Comercial Titán Plaza"
  ],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-018",
  "tipo": "Informativa",
  "nombre": "Estructura – Clasificación Canales, Subcanales",
  "grupo": "Todos",
  "dirigida": "Todos",
  "producto": "Todos",
  "ini": "2026-06-01",
  "fin": "",
  "objetivo": "Informar cambios y creaciones de canales, subcanales y condiciones comerciales",
  "resumen": "Crea las clasificaciones 12, 13, 14, 70 y 71 y sus condiciones: 13 y 14 plazo 30 días, dcto 8% y bonificación 6+1; 70 dcto 25% en terminados y 16% en magistrales, 10+2; 71 dcto 12% y 6+1; 12 no factura.",
  "obs": "",
  "pdf": "",
  "productos": [],
  "canales": [],
  "clientes": [],
  "excluidos": [],
  "todos": true,
  "interna": false
 },
 {
  "c": "2026-019",
  "tipo": "Alcance",
  "nombre": "Alcance a la circular 2026-009",
  "grupo": "Magistral de Pedido / Producto Terminado",
  "dirigida": "Canales 20, 21, 22",
  "producto": "[PT0014], [PT0003], [PT0004], [MP0676], [MP0738], [MP0570]",
  "ini": "2026-07-01",
  "fin": "2026-07-31",
  "objetivo": "Prorrogar un mes más la parrilla promocional de la circular 2026-009",
  "resumen": "Alcance a la circular 2026-009: extiende durante julio de 2026 la parrilla promocional de abril-junio para los canales 20, 21 y 22, con los mismos productos y condiciones.",
  "obs": "Prórroga de 2026-009",
  "pdf": "",
  "productos": [
   {
    "c": "PT0014",
    "n": ""
   },
   {
    "c": "PT0003",
    "n": ""
   },
   {
    "c": "PT0004",
    "n": ""
   },
   {
    "c": "MP0676",
    "n": ""
   },
   {
    "c": "MP0738",
    "n": ""
   },
   {
    "c": "MP0570",
    "n": ""
   }
  ],
  "canales": [
   "20",
   "21",
   "22"
  ],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-020",
  "tipo": "Evacuación",
  "nombre": "Acuerdo Comercial Bellapiel",
  "grupo": "Producto Terminado / Magistrales",
  "dirigida": "Bella Piel S.A.S.",
  "producto": "Todo el portafolio",
  "ini": "2026-01-01",
  "fin": "2026-12-31",
  "objetivo": "Acuerdo comercial con Bella Piel: inversión hasta 8% trimestral y participación en mercadeo",
  "resumen": "Meta de crecer 15%-25% sobre las ventas de 2025 con rebates de 3%, 5% o 7% por crecimiento, 1% en NC trimestral por información de Sell In/Sell Out y 6 jornadas comerciales al año (Aniversario y Black). Incluye descuento por pronto pago.",
  "obs": "",
  "pdf": "",
  "productos": [],
  "canales": [],
  "clientes": [
   "Bella Piel S.A.S.",
   "Bella Piel S.A.S., Bella Piel Acomedica (AM)",
   "Bella Piel S.A.S., Bella Piel Bodega Distribucion (BDP)",
   "Bella Piel S.A.S., Bella Piel C.C Avenida Chile (AC)",
   "Bella Piel S.A.S., Bella Piel C.C Babilla Plaza (CB)",
   "Bella Piel S.A.S., Bella Piel C.C Buenavista (MN)",
   "Bella Piel S.A.S., Bella Piel C.C Caribe Plaza (CP)",
   "Bella Piel S.A.S., Bella Piel C.C Cañaveral (BC)",
   "Bella Piel S.A.S., Bella Piel C.C Cañaveral (BV)",
   "Bella Piel S.A.S., Bella Piel C.C Cedritos (CD)",
   "Bella Piel S.A.S., Bella Piel C.C Centro Suba (SU)",
   "Bella Piel S.A.S., Bella Piel C.C City Medica (MX)",
   "Bella Piel S.A.S., Bella Piel C.C Gran Plaza San Antonio (GT)",
   "Bella Piel S.A.S., Bella Piel C.C Gran Plaza Soacha (PG)",
   "Bella Piel S.A.S., Bella Piel C.C Gran Plaza el Sol (BS)",
   "Bella Piel S.A.S., Bella Piel C.C Granada Meta (ZG)",
   "Bella Piel S.A.S., Bella Piel C.C Jardin Plaza (JC)",
   "Bella Piel S.A.S., Bella Piel C.C La Casona Ph (CZ)",
   "Bella Piel S.A.S., Bella Piel C.C Los Caobos (LC)",
   "Bella Piel S.A.S., Bella Piel C.C Metropolis (ME)",
   "Bella Piel S.A.S., Bella Piel C.C Plaza Claro (PO)",
   "Bella Piel S.A.S., Bella Piel C.C Plaza Imperial 133 (IP)",
   "Bella Piel S.A.S., Bella Piel C.C Plaza de las Americas (AP)",
   "Bella Piel S.A.S., Bella Piel C.C Puerta del Norte (MH)",
   "Bella Piel S.A.S., Bella Piel C.C Salitre Plaza (PS)",
   "Bella Piel S.A.S., Bella Piel C.C San Diego 1485 (SD)",
   "Bella Piel S.A.S., Bella Piel C.C San Nicolas (MQ)",
   "Bella Piel S.A.S., Bella Piel C.C Santa Barbara (HB)",
   "Bella Piel S.A.S., Bella Piel C.C Santa Fe (SV)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Armenia (UA)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Cali 447 (UC)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Neiva (UN)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Pasto (PU)",
   "Bella Piel S.A.S., Bella Piel C.C Ventura Cucuta (VC)",
   "Bella Piel S.A.S., Bella Piel C.C Viva Wajira (VG)",
   "Bella Piel S.A.S., Bella Piel C.C Viva la Ceja (AL)",
   "Bella Piel S.A.S., Bella Piel C.C. Andino (AN)",
   "Bella Piel S.A.S., Bella Piel C.C. Arkadia (MA)",
   "Bella Piel S.A.S., Bella Piel C.C. Avenida (AF)",
   "Bella Piel S.A.S., Bella Piel C.C. Buenavista (BU)",
   "Bella Piel S.A.S., Bella Piel C.C. Cafam Floresta (CF)",
   "Bella Piel S.A.S., Bella Piel C.C. Calima (CC)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Chia (CH)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Logistico (PW)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Mayor (CM)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Mayor (CN)",
   "Bella Piel S.A.S., Bella Piel C.C. Chipichape (CA)",
   "Bella Piel S.A.S., Bella Piel C.C. Cosmocentro (CO)",
   "Bella Piel S.A.S., Bella Piel C.C. Diver Plaza (DP)",
   "Bella Piel S.A.S., Bella Piel C.C. Ecoplaza (EC)",
   "Bella Piel S.A.S., Bella Piel C.C. Edificio Torre Palatino (EP)",
   "Bella Piel S.A.S., Bella Piel C.C. El Tesoro Parque Comercial (MT)",
   "Bella Piel S.A.S., Bella Piel C.C. Florida Parque Comercial (ML)",
   "Bella Piel S.A.S., Bella Piel C.C. Fontanar (FT)",
   "Bella Piel S.A.S., Bella Piel C.C. Fundadores (FM)",
   "Bella Piel S.A.S., Bella Piel C.C. Galerias (GA)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Estacion (GE)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Estacion (GN)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Plaza - La Libertad (FP)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Plaza Alcaravan (AY)",
   "Bella Piel S.A.S., Bella Piel C.C. Guatapuri (UV)",
   "Bella Piel S.A.S., Bella Piel C.C. Hacienda Santa Barbara (HN)",
   "Bella Piel S.A.S., Bella Piel C.C. Hacienda Santa Barbara (HS)",
   "Bella Piel S.A.S., Bella Piel C.C. Hayuelos (HY)",
   "Bella Piel S.A.S., Bella Piel C.C. Holguines Trade Center (CG)",
   "Bella Piel S.A.S., Bella Piel C.C. Innovo Plaza (DI)",
   "Bella Piel S.A.S., Bella Piel C.C. Jardin Plaza (CJ)",
   "Bella Piel S.A.S., Bella Piel C.C. La Estacion (EI)",
   "Bella Piel S.A.S., Bella Piel C.C. La Estacion (LI)",
   "Bella Piel S.A.S., Bella Piel C.C. La Mansion (BB)",
   "Bella Piel S.A.S., Bella Piel C.C. Mall Plaza (BM)",
   "Bella Piel S.A.S., Bella Piel C.C. Mall Plaza Buenavista (BA)",
   "Bella Piel S.A.S., Bella Piel C.C. Mayorca (MY)",
   "Bella Piel S.A.S., Bella Piel C.C. Mercurio (MB)",
   "Bella Piel S.A.S., Bella Piel C.C. Molinos (MM)",
   "Bella Piel S.A.S., Bella Piel C.C. Multicentro Ibague (MI)",
   "Bella Piel S.A.S., Bella Piel C.C. Multiplaza (MF)",
   "Bella Piel S.A.S., Bella Piel C.C. Nuestro Bogota (NB)",
   "Bella Piel S.A.S., Bella Piel C.C. Nuestro Cartago (NC)",
   "Bella Piel S.A.S., Bella Piel C.C. Palatino (PL)",
   "Bella Piel S.A.S., Bella Piel C.C. Parque Alegra (BL)",
   "Bella Piel S.A.S., Bella Piel C.C. Parque la Colina (CE)",
   "Bella Piel S.A.S., Bella Piel C.C. Paseo Villa del Rio (PR)",
   "Bella Piel S.A.S., Bella Piel C.C. Pereira Plaza (PP)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza Central (PC)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza De Las Americas (PZ)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza Imperial (PI)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza Mayor (BP)",
   "Bella Piel S.A.S., Bella Piel C.C. Portal 80 (PN)",
   "Bella Piel S.A.S., Bella Piel C.C. Portal Quindio (PQ)",
   "Bella Piel S.A.S., Bella Piel C.C. Premium Plaza (MP)",
   "Bella Piel S.A.S., Bella Piel C.C. Primavera Urbana (VP)",
   "Bella Piel S.A.S., Bella Piel C.C. Salitre Plaza (SA)",
   "Bella Piel S.A.S., Bella Piel C.C. San Diego (MD)",
   "Bella Piel S.A.S., Bella Piel C.C. San Pedro (NS)",
   "Bella Piel S.A.S., Bella Piel C.C. Santa Fe (SN)",
   "Bella Piel S.A.S., Bella Piel C.C. Santa Fe Jumbo (SP)",
   "Bella Piel S.A.S., Bella Piel C.C. Santa Lucia Plaza (BN)",
   "Bella Piel S.A.S., Bella Piel C.C. Santafe (MS)",
   "Bella Piel S.A.S., Bella Piel C.C. Suchiima (RS)",
   "Bella Piel S.A.S., Bella Piel C.C. Titan Plaza (TE)",
   "Bella Piel S.A.S., Bella Piel C.C. Titan Plaza (TN)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro (CU)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro (UE)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Girardot (UG)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Medellin (MU)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Occidente (UO)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Primer Piso (UP)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Tunja (UT)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Villavicencio (VU)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Yopal (UY)",
   "Bella Piel S.A.S., Bella Piel C.C. Ventura Terreros (TB)",
   "Bella Piel S.A.S., Bella Piel C.C. Viva Barranquilla (BI)",
   "Bella Piel S.A.S., Bella Piel C.C. Viva Tunja (VT)",
   "Bella Piel S.A.S., Bella Piel C.C. Viva Villavicencio (VB)",
   "Bella Piel S.A.S., Bella Piel CC. La Quinta (BQ)",
   "Bella Piel S.A.S., Bella Piel Campanario (LC)",
   "Bella Piel S.A.S., Bella Piel Castellana 98 Isla (LL)",
   "Bella Piel S.A.S., Bella Piel Centro Especialista Cl 90 (CS)",
   "Bella Piel S.A.S., Bella Piel Centro Internacional de Especialistas (BE)",
   "Bella Piel S.A.S., Bella Piel Centro Mayor (CR)",
   "Bella Piel S.A.S., Bella Piel Centro Medico Calle 91 (NO)",
   "Bella Piel S.A.S., Bella Piel Centro Medico de la Sabana (SB)",
   "Bella Piel S.A.S., Bella Piel Clinica Porto Azul (BJ)",
   "Bella Piel S.A.S., Bella Piel Colina 153 Isla (IC)",
   "Bella Piel S.A.S., Bella Piel Edificio Castellana 98 (LL)",
   "Bella Piel S.A.S., Bella Piel Edificio Colon Corporacion Medico Empresarial PH- Las Nieves (CT)",
   "Bella Piel S.A.S., Bella Piel Edificio Global Medical Center (GM)",
   "Bella Piel S.A.S., Bella Piel Edificio North West 94 (NW)",
   "Bella Piel S.A.S., Bella Piel Edificio Salud y Servicios PH (MR)",
   "Bella Piel S.A.S., Bella Piel Edificio San Sebastián del Country (SS)",
   "Bella Piel S.A.S., Bella Piel Edificio Santa Ana Medical Center (SM)",
   "Bella Piel S.A.S., Bella Piel Edificio Torres Zentai (TZ)",
   "Bella Piel S.A.S., Bella Piel El Country (ZC)",
   "Bella Piel S.A.S., Bella Piel Florida Parque Comercial (LM)",
   "Bella Piel S.A.S., Bella Piel Gradeco Business Plaza (EG)",
   "Bella Piel S.A.S., Bella Piel Hayuelos (HA)",
   "Bella Piel S.A.S., Bella Piel Hospital Universitario La Fundacion Santafe De Bogota (FS)",
   "Bella Piel S.A.S., Bella Piel Llanogrande Plaza (VL)",
   "Bella Piel S.A.S., Bella Piel Mall Plaza Cartagena (CX)",
   "Bella Piel S.A.S., Bella Piel Mall Plaza Manizales (PM)",
   "Bella Piel S.A.S., Bella Piel Micentro Funza PH (FZ)",
   "Bella Piel S.A.S., Bella Piel North West Isla (NW)",
   "Bella Piel S.A.S., Bella Piel Pacific Center (CK)",
   "Bella Piel S.A.S., Bella Piel Palmetto Plaza 134 (TC)",
   "Bella Piel S.A.S., Bella Piel Parque Comercial Guacarí Sincelejo (GS)",
   "Bella Piel S.A.S., Bella Piel Pasaje Astoria (MJ)",
   "Bella Piel S.A.S., Bella Piel Proyecto de Vida Centro Profesional PH (CV)",
   "Bella Piel S.A.S., Bella Piel S.A.S C.C Gran Estacion (GO)",
   "Bella Piel S.A.S., Bella Piel S.A.S C.C Mayorca (YM)",
   "Bella Piel S.A.S., Bella Piel S.A.S C.C Palatino (LP)",
   "Bella Piel S.A.S., Bella Piel S.A.S Centro Comercial Plaza Imperial(PE)",
   "Bella Piel S.A.S., Bella Piel S.A.S., Centro Logistico (DM)",
   "Bella Piel S.A.S., Bella Piel Sabana Park Health & Businees (SH)",
   "Bella Piel S.A.S., Bella Piel Salud Vegas Torre Medica PH (MV)",
   "Bella Piel S.A.S., Bella Piel San Nicolas 2369 (MW)",
   "Bella Piel S.A.S., Bella Piel Supercentro Tulua la 14 (TS)",
   "Bella Piel S.A.S., Bella Piel Zonata Centro Medico (ZO)",
   "Tienda Dermocosmetica Bella Piel, Juanita Ceron Delgado"
  ],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-021",
  "tipo": "Negociación",
  "nombre": "Participación aniversario Bellapiel",
  "grupo": "Producto Terminado / Magistral de Pedido / Magistral Individual",
  "dirigida": "Bella Piel S.A.S.",
  "producto": "Todo el portafolio",
  "ini": "2026-05-01",
  "fin": "2026-05-31",
  "objetivo": "Participar como marca aliada en la campaña del aniversario 22 de Bella Piel",
  "resumen": "Epithelium aporta $3.000.000 a la estrategia de mercadeo 360° del aniversario de Bella Piel, que incluye la marca (producto terminado) en los medios de la campaña. Bella Piel entrega informe de cierre y con él se genera la Nota Crédito.",
  "obs": "Aporte de $3.000.000 de Epithelium",
  "pdf": "",
  "productos": [],
  "canales": [],
  "clientes": [
   "Bella Piel S.A.S.",
   "Bella Piel S.A.S., Bella Piel Acomedica (AM)",
   "Bella Piel S.A.S., Bella Piel Bodega Distribucion (BDP)",
   "Bella Piel S.A.S., Bella Piel C.C Avenida Chile (AC)",
   "Bella Piel S.A.S., Bella Piel C.C Babilla Plaza (CB)",
   "Bella Piel S.A.S., Bella Piel C.C Buenavista (MN)",
   "Bella Piel S.A.S., Bella Piel C.C Caribe Plaza (CP)",
   "Bella Piel S.A.S., Bella Piel C.C Cañaveral (BC)",
   "Bella Piel S.A.S., Bella Piel C.C Cañaveral (BV)",
   "Bella Piel S.A.S., Bella Piel C.C Cedritos (CD)",
   "Bella Piel S.A.S., Bella Piel C.C Centro Suba (SU)",
   "Bella Piel S.A.S., Bella Piel C.C City Medica (MX)",
   "Bella Piel S.A.S., Bella Piel C.C Gran Plaza San Antonio (GT)",
   "Bella Piel S.A.S., Bella Piel C.C Gran Plaza Soacha (PG)",
   "Bella Piel S.A.S., Bella Piel C.C Gran Plaza el Sol (BS)",
   "Bella Piel S.A.S., Bella Piel C.C Granada Meta (ZG)",
   "Bella Piel S.A.S., Bella Piel C.C Jardin Plaza (JC)",
   "Bella Piel S.A.S., Bella Piel C.C La Casona Ph (CZ)",
   "Bella Piel S.A.S., Bella Piel C.C Los Caobos (LC)",
   "Bella Piel S.A.S., Bella Piel C.C Metropolis (ME)",
   "Bella Piel S.A.S., Bella Piel C.C Plaza Claro (PO)",
   "Bella Piel S.A.S., Bella Piel C.C Plaza Imperial 133 (IP)",
   "Bella Piel S.A.S., Bella Piel C.C Plaza de las Americas (AP)",
   "Bella Piel S.A.S., Bella Piel C.C Puerta del Norte (MH)",
   "Bella Piel S.A.S., Bella Piel C.C Salitre Plaza (PS)",
   "Bella Piel S.A.S., Bella Piel C.C San Diego 1485 (SD)",
   "Bella Piel S.A.S., Bella Piel C.C San Nicolas (MQ)",
   "Bella Piel S.A.S., Bella Piel C.C Santa Barbara (HB)",
   "Bella Piel S.A.S., Bella Piel C.C Santa Fe (SV)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Armenia (UA)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Cali 447 (UC)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Neiva (UN)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Pasto (PU)",
   "Bella Piel S.A.S., Bella Piel C.C Ventura Cucuta (VC)",
   "Bella Piel S.A.S., Bella Piel C.C Viva Wajira (VG)",
   "Bella Piel S.A.S., Bella Piel C.C Viva la Ceja (AL)",
   "Bella Piel S.A.S., Bella Piel C.C. Andino (AN)",
   "Bella Piel S.A.S., Bella Piel C.C. Arkadia (MA)",
   "Bella Piel S.A.S., Bella Piel C.C. Avenida (AF)",
   "Bella Piel S.A.S., Bella Piel C.C. Buenavista (BU)",
   "Bella Piel S.A.S., Bella Piel C.C. Cafam Floresta (CF)",
   "Bella Piel S.A.S., Bella Piel C.C. Calima (CC)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Chia (CH)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Logistico (PW)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Mayor (CM)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Mayor (CN)",
   "Bella Piel S.A.S., Bella Piel C.C. Chipichape (CA)",
   "Bella Piel S.A.S., Bella Piel C.C. Cosmocentro (CO)",
   "Bella Piel S.A.S., Bella Piel C.C. Diver Plaza (DP)",
   "Bella Piel S.A.S., Bella Piel C.C. Ecoplaza (EC)",
   "Bella Piel S.A.S., Bella Piel C.C. Edificio Torre Palatino (EP)",
   "Bella Piel S.A.S., Bella Piel C.C. El Tesoro Parque Comercial (MT)",
   "Bella Piel S.A.S., Bella Piel C.C. Florida Parque Comercial (ML)",
   "Bella Piel S.A.S., Bella Piel C.C. Fontanar (FT)",
   "Bella Piel S.A.S., Bella Piel C.C. Fundadores (FM)",
   "Bella Piel S.A.S., Bella Piel C.C. Galerias (GA)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Estacion (GE)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Estacion (GN)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Plaza - La Libertad (FP)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Plaza Alcaravan (AY)",
   "Bella Piel S.A.S., Bella Piel C.C. Guatapuri (UV)",
   "Bella Piel S.A.S., Bella Piel C.C. Hacienda Santa Barbara (HN)",
   "Bella Piel S.A.S., Bella Piel C.C. Hacienda Santa Barbara (HS)",
   "Bella Piel S.A.S., Bella Piel C.C. Hayuelos (HY)",
   "Bella Piel S.A.S., Bella Piel C.C. Holguines Trade Center (CG)",
   "Bella Piel S.A.S., Bella Piel C.C. Innovo Plaza (DI)",
   "Bella Piel S.A.S., Bella Piel C.C. Jardin Plaza (CJ)",
   "Bella Piel S.A.S., Bella Piel C.C. La Estacion (EI)",
   "Bella Piel S.A.S., Bella Piel C.C. La Estacion (LI)",
   "Bella Piel S.A.S., Bella Piel C.C. La Mansion (BB)",
   "Bella Piel S.A.S., Bella Piel C.C. Mall Plaza (BM)",
   "Bella Piel S.A.S., Bella Piel C.C. Mall Plaza Buenavista (BA)",
   "Bella Piel S.A.S., Bella Piel C.C. Mayorca (MY)",
   "Bella Piel S.A.S., Bella Piel C.C. Mercurio (MB)",
   "Bella Piel S.A.S., Bella Piel C.C. Molinos (MM)",
   "Bella Piel S.A.S., Bella Piel C.C. Multicentro Ibague (MI)",
   "Bella Piel S.A.S., Bella Piel C.C. Multiplaza (MF)",
   "Bella Piel S.A.S., Bella Piel C.C. Nuestro Bogota (NB)",
   "Bella Piel S.A.S., Bella Piel C.C. Nuestro Cartago (NC)",
   "Bella Piel S.A.S., Bella Piel C.C. Palatino (PL)",
   "Bella Piel S.A.S., Bella Piel C.C. Parque Alegra (BL)",
   "Bella Piel S.A.S., Bella Piel C.C. Parque la Colina (CE)",
   "Bella Piel S.A.S., Bella Piel C.C. Paseo Villa del Rio (PR)",
   "Bella Piel S.A.S., Bella Piel C.C. Pereira Plaza (PP)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza Central (PC)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza De Las Americas (PZ)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza Imperial (PI)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza Mayor (BP)",
   "Bella Piel S.A.S., Bella Piel C.C. Portal 80 (PN)",
   "Bella Piel S.A.S., Bella Piel C.C. Portal Quindio (PQ)",
   "Bella Piel S.A.S., Bella Piel C.C. Premium Plaza (MP)",
   "Bella Piel S.A.S., Bella Piel C.C. Primavera Urbana (VP)",
   "Bella Piel S.A.S., Bella Piel C.C. Salitre Plaza (SA)",
   "Bella Piel S.A.S., Bella Piel C.C. San Diego (MD)",
   "Bella Piel S.A.S., Bella Piel C.C. San Pedro (NS)",
   "Bella Piel S.A.S., Bella Piel C.C. Santa Fe (SN)",
   "Bella Piel S.A.S., Bella Piel C.C. Santa Fe Jumbo (SP)",
   "Bella Piel S.A.S., Bella Piel C.C. Santa Lucia Plaza (BN)",
   "Bella Piel S.A.S., Bella Piel C.C. Santafe (MS)",
   "Bella Piel S.A.S., Bella Piel C.C. Suchiima (RS)",
   "Bella Piel S.A.S., Bella Piel C.C. Titan Plaza (TE)",
   "Bella Piel S.A.S., Bella Piel C.C. Titan Plaza (TN)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro (CU)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro (UE)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Girardot (UG)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Medellin (MU)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Occidente (UO)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Primer Piso (UP)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Tunja (UT)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Villavicencio (VU)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Yopal (UY)",
   "Bella Piel S.A.S., Bella Piel C.C. Ventura Terreros (TB)",
   "Bella Piel S.A.S., Bella Piel C.C. Viva Barranquilla (BI)",
   "Bella Piel S.A.S., Bella Piel C.C. Viva Tunja (VT)",
   "Bella Piel S.A.S., Bella Piel C.C. Viva Villavicencio (VB)",
   "Bella Piel S.A.S., Bella Piel CC. La Quinta (BQ)",
   "Bella Piel S.A.S., Bella Piel Campanario (LC)",
   "Bella Piel S.A.S., Bella Piel Castellana 98 Isla (LL)",
   "Bella Piel S.A.S., Bella Piel Centro Especialista Cl 90 (CS)",
   "Bella Piel S.A.S., Bella Piel Centro Internacional de Especialistas (BE)",
   "Bella Piel S.A.S., Bella Piel Centro Mayor (CR)",
   "Bella Piel S.A.S., Bella Piel Centro Medico Calle 91 (NO)",
   "Bella Piel S.A.S., Bella Piel Centro Medico de la Sabana (SB)",
   "Bella Piel S.A.S., Bella Piel Clinica Porto Azul (BJ)",
   "Bella Piel S.A.S., Bella Piel Colina 153 Isla (IC)",
   "Bella Piel S.A.S., Bella Piel Edificio Castellana 98 (LL)",
   "Bella Piel S.A.S., Bella Piel Edificio Colon Corporacion Medico Empresarial PH- Las Nieves (CT)",
   "Bella Piel S.A.S., Bella Piel Edificio Global Medical Center (GM)",
   "Bella Piel S.A.S., Bella Piel Edificio North West 94 (NW)",
   "Bella Piel S.A.S., Bella Piel Edificio Salud y Servicios PH (MR)",
   "Bella Piel S.A.S., Bella Piel Edificio San Sebastián del Country (SS)",
   "Bella Piel S.A.S., Bella Piel Edificio Santa Ana Medical Center (SM)",
   "Bella Piel S.A.S., Bella Piel Edificio Torres Zentai (TZ)",
   "Bella Piel S.A.S., Bella Piel El Country (ZC)",
   "Bella Piel S.A.S., Bella Piel Florida Parque Comercial (LM)",
   "Bella Piel S.A.S., Bella Piel Gradeco Business Plaza (EG)",
   "Bella Piel S.A.S., Bella Piel Hayuelos (HA)",
   "Bella Piel S.A.S., Bella Piel Hospital Universitario La Fundacion Santafe De Bogota (FS)",
   "Bella Piel S.A.S., Bella Piel Llanogrande Plaza (VL)",
   "Bella Piel S.A.S., Bella Piel Mall Plaza Cartagena (CX)",
   "Bella Piel S.A.S., Bella Piel Mall Plaza Manizales (PM)",
   "Bella Piel S.A.S., Bella Piel Micentro Funza PH (FZ)",
   "Bella Piel S.A.S., Bella Piel North West Isla (NW)",
   "Bella Piel S.A.S., Bella Piel Pacific Center (CK)",
   "Bella Piel S.A.S., Bella Piel Palmetto Plaza 134 (TC)",
   "Bella Piel S.A.S., Bella Piel Parque Comercial Guacarí Sincelejo (GS)",
   "Bella Piel S.A.S., Bella Piel Pasaje Astoria (MJ)",
   "Bella Piel S.A.S., Bella Piel Proyecto de Vida Centro Profesional PH (CV)",
   "Bella Piel S.A.S., Bella Piel S.A.S C.C Gran Estacion (GO)",
   "Bella Piel S.A.S., Bella Piel S.A.S C.C Mayorca (YM)",
   "Bella Piel S.A.S., Bella Piel S.A.S C.C Palatino (LP)",
   "Bella Piel S.A.S., Bella Piel S.A.S Centro Comercial Plaza Imperial(PE)",
   "Bella Piel S.A.S., Bella Piel S.A.S., Centro Logistico (DM)",
   "Bella Piel S.A.S., Bella Piel Sabana Park Health & Businees (SH)",
   "Bella Piel S.A.S., Bella Piel Salud Vegas Torre Medica PH (MV)",
   "Bella Piel S.A.S., Bella Piel San Nicolas 2369 (MW)",
   "Bella Piel S.A.S., Bella Piel Supercentro Tulua la 14 (TS)",
   "Bella Piel S.A.S., Bella Piel Zonata Centro Medico (ZO)",
   "Tienda Dermocosmetica Bella Piel, Juanita Ceron Delgado"
  ],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-022",
  "tipo": "Evacuación",
  "nombre": "Actividad promocional portafolio Epithelium",
  "grupo": "Magistral de Pedido / Producto Terminado",
  "dirigida": "Dermatology S.A.S.",
  "producto": "Magistral de Pedido y Producto Terminado",
  "ini": "2026-08-04",
  "fin": "2026-08-09",
  "objetivo": "Crecer mínimo 20% las ventas de productos participantes con una semana de descuentos",
  "resumen": "Semana de descuentos del 4 al 9 de agosto en Dermatology S.A.S.: 10% sobre el costo de venta antes de IVA vía POS. Requiere inventario inicial y final y tirillas de venta; datos a más tardar el 15/08 y Nota Crédito el 28 de agosto de 2026.",
  "obs": "Descuento 10%; NC el 28/08/2026",
  "pdf": "",
  "productos": [],
  "canales": [],
  "clientes": [
   "Dermatology S.A.S."
  ],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-023",
  "tipo": "Evacuación",
  "nombre": "Salud y belleza llanera",
  "grupo": "Producto Terminado",
  "dirigida": "Más Piel, Dermatology, Dermomedic",
  "producto": "Todos los terminados",
  "ini": "2026-08-10",
  "fin": "2026-09-30",
  "objetivo": "Apoyar al cliente en sus días de descuento para atraer compradores",
  "resumen": "Descuento de 15% sobre el costo de venta antes de IVA los viernes y sábados de agosto y septiembre en Más Piel, Dermatology y Dermomedic. El cliente reporta ventas POS y se liquida con Nota Crédito entre el 15 y el 16 de octubre de 2026.",
  "obs": "Descuento 15% viernes y sábado; NC el 15-16/10/2026",
  "pdf": "",
  "productos": [],
  "canales": [],
  "clientes": [
   "Dermatology S.A.S.",
   "Dermomedic Health, Carlos David Garcia Gomez",
   "Mas Piel LTDA"
  ],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-024",
  "tipo": "Colocación",
  "nombre": "Longevidad con Revival 2026",
  "grupo": "Terminados",
  "dirigida": "Subcanales 20, 21, 22",
  "producto": "[PT0003] Revival Crema x 50 g",
  "ini": "2026-08-01",
  "fin": "2026-09-30",
  "objetivo": "Colocar 100 unidades de Revival en el grupo objetivo durante agosto y septiembre",
  "resumen": "El médico recibe $10.000 en Protocolo Médico por cada unidad de Revival formulada y reportada (duplica la retribución). Se apoya con visita presencial, tester, WhatsApp y redes. Dirigida a subcanales 20, 21 y 22.",
  "obs": "Meta 100 unidades; $10.000 por unidad en Protocolo Médico",
  "pdf": "",
  "productos": [
   {
    "c": "PT0003",
    "n": "Revival Crema x 50 g"
   }
  ],
  "canales": [
   "20",
   "21",
   "22"
  ],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-025",
  "tipo": "Evacuación",
  "nombre": "Parrilla Promocional. Agosto - Octubre",
  "grupo": "Magistral de Pedido / Producto Terminado",
  "dirigida": "Canales 20, 21, 22",
  "producto": "[MA0373] Bimatoprost; [MA0156] Flutamida; [PT0014]; [MP0912]; [MP0734]; [PT0003]",
  "ini": "2026-08-01",
  "fin": "2026-10-31",
  "objetivo": "Presentar la parrilla promocional al 100% del panel médico, con 1 impacto mensual",
  "resumen": "Parrilla agosto-octubre para canales 20, 21 y 22: Bimatoprost, Flutamida, Capilplus Acondicionador, Serum Cejas y Pestañas, Minobit N y Revival. Visita mensual (presencial en Bogotá, virtual en regiones) y refuerzo semanal.",
  "obs": "",
  "pdf": "",
  "productos": [
   {
    "c": "MA0373",
    "n": "Bimatoprost"
   },
   {
    "c": "MA0156",
    "n": "Flutamida"
   },
   {
    "c": "PT0014",
    "n": ""
   },
   {
    "c": "MP0912",
    "n": ""
   },
   {
    "c": "MP0734",
    "n": ""
   },
   {
    "c": "PT0003",
    "n": ""
   }
  ],
  "canales": [
   "20",
   "21",
   "22"
  ],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-026",
  "tipo": "Colocación",
  "nombre": "Impulsa la Formulación y Gana Más",
  "grupo": "Magistral de Pedido",
  "dirigida": "Canales 20, 21, 22",
  "producto": "[MP0912] Serum Cejas y Pestañas; [MP0734] Minobit N Espuma",
  "ini": "2026-08-01",
  "fin": "2026-10-31",
  "objetivo": "Impulsar la formulación de Serum Cejas y Pestañas y Minobit N con incentivo al médico",
  "resumen": "El médico recibe $4.000 por unidad de Serum Reparador Cejas y Pestañas y $12.000 por unidad de Minobit N Espuma, evacuada y reportada en Protocolo Médico. Reemplaza el porcentaje habitual y no se acumula con otros beneficios.",
  "obs": "$4.000 y $12.000 por unidad en Protocolo Médico",
  "pdf": "",
  "productos": [
   {
    "c": "MP0912",
    "n": "Serum Cejas y Pestañas"
   },
   {
    "c": "MP0734",
    "n": "Minobit N Espuma"
   }
  ],
  "canales": [
   "20",
   "21",
   "22"
  ],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-027",
  "tipo": "Evacuación",
  "nombre": "Compra y Protege con Epithelium",
  "grupo": "Magistrales de pedido",
  "dirigida": "Canales 90, 11, 13, 21, 22, 31, 50, 60, 61, 70, 71",
  "producto": "[MP0640] Gel Antibacterial x 1000 ml (obsequio)",
  "ini": "2026-08-05",
  "fin": "2026-08-31",
  "objetivo": "Evacuar 100 unidades del Gel Antibacterial x 1000 ml e incentivar la rotación",
  "resumen": "Clientes con compras de magistrales de pedido desde $1.500.000 reciben 1 Gel Antibacterial x 1000 ml de obsequio (una por factura) hasta agotar 100 unidades. Se carga en Odoo con nota interna.",
  "obs": "El PDF dice año 2025; se asumió 2026. Compras desde $1.500.000; 100 unidades",
  "pdf": "",
  "productos": [
   {
    "c": "MP0640",
    "n": "Gel Antibacterial x 1000 ml (obsequio)"
   }
  ],
  "canales": [
   "11",
   "13",
   "21",
   "22",
   "31",
   "50",
   "60",
   "61",
   "70",
   "71",
   "90"
  ],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-028",
  "tipo": "Colocación",
  "nombre": "Bonificación especial por codificación",
  "grupo": "Magistral de Pedido",
  "dirigida": "Canales 10, 11, 13, 20, 21, 90, 50, 70, 71",
  "producto": "[MP0734] Minobit N Espuma x 200 ml",
  "ini": "2026-08-04",
  "fin": "2026-09-30",
  "objetivo": "Colocar 60 unidades en el lanzamiento de Minobit N Espuma e impulsar su codificación",
  "resumen": "Bonificación de lanzamiento de Minobit N Espuma x 200 ml: 5+2 en canales 20 y 90 y 5+1 en los demás canales. Se gestiona en Odoo con aprobación de Gerencia General.",
  "obs": "Bonificación 5+2 (canal 90) y 5+1 (demás)",
  "pdf": "",
  "productos": [
   {
    "c": "MP0734",
    "n": "Minobit N Espuma x 200 ml"
   }
  ],
  "canales": [
   "10",
   "11",
   "13",
   "20",
   "21",
   "50",
   "70",
   "71",
   "90"
  ],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-030",
  "tipo": "Evacuación",
  "nombre": "Morado Days – Línea Estética",
  "grupo": "Producto Terminado",
  "dirigida": "CMX S.A.S. (Línea Estética)",
  "producto": "Todos los productos terminados",
  "ini": "2026-08-28",
  "fin": "2026-08-31",
  "objetivo": "Apoyar a CMX (Línea Estética) en la campaña Morado Days con producto terminado",
  "resumen": "4 días de descuento del 20% sobre el costo de venta antes de IVA, del 28 al 31 de agosto, en todo el portafolio de terminados, en tienda y online. El cliente envía ventas POS y se liquida con Nota Crédito entre el 9 y el 16 de septiembre.",
  "obs": "Descuento 20%",
  "pdf": "",
  "productos": [],
  "canales": [],
  "clientes": [
   "CMX S.A.S, Linea Estetica Centro Comercial Titán Plaza"
  ],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-031",
  "tipo": "Alcance",
  "nombre": "Alcance circular 2026-027 Compra y Protege",
  "grupo": "Magistrales de pedido",
  "dirigida": "Canales 90, 11, 13, 21, 22, 31, 50, 60, 61, 70, 71",
  "producto": "[MP0640] Gel Antibacterial x 1000 ml",
  "ini": "2026-08-01",
  "fin": "2026-08-31",
  "objetivo": "Corregir el código del Gel Antibacterial x 1000 ml [MP0640] de la circular 2026-027",
  "resumen": "Alcance a la circular 2026-027: corrige en las argumentaciones de médico y cliente el código del obsequio [MP0640] Gel Antibacterial x 1000 ml (compras desde $1.500.000, hasta agotar 100 unidades).",
  "obs": "El PDF dice año 2025; se asumió 2026. Corrige código del producto",
  "pdf": "",
  "productos": [
   {
    "c": "MP0640",
    "n": "Gel Antibacterial x 1000 ml"
   }
  ],
  "canales": [
   "11",
   "13",
   "21",
   "22",
   "31",
   "50",
   "60",
   "61",
   "70",
   "71",
   "90"
  ],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-032",
  "tipo": "Anulada",
  "nombre": "Circular anulada",
  "grupo": "",
  "dirigida": "N/A",
  "producto": "",
  "ini": "",
  "fin": "",
  "objetivo": "",
  "resumen": "La circular 2026-032 quedó anulada: no se presentó.",
  "obs": "Anulada. No se presentó",
  "pdf": "",
  "productos": [],
  "canales": [],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-033",
  "tipo": "Codificación y colocación",
  "nombre": "Bonificado Cruzado",
  "grupo": "Producto Terminado",
  "dirigida": "Canales 90, 10, 11, 50, 51, 61, 70 (no aplica Bella Piel)",
  "producto": "[PT0005] Sunskin Oil Free x 80 g, [PT0011] Capilplus Shampoo x 220 ml, [PT0001] Hydrafort Face x 50 g, [PT0014] Capilplus Acondicionador x 220 ml, [PT0003] Revival Crema x 50 g, [PT0012] Sensibath x 240 ml, [PT0002] Capilplus DS Shampoo Anticaspa x 220 ml, [PT0004] Hydrafort pH5 Ultrahumectante Crema x 250 g, [PT0010] Sunskin SPF 50+ Emulsión x 80 g",
  "ini": "2026-10-06",
  "fin": "2026-11-30",
  "objetivo": "Impulsar la compra y codificación de los terminados de menor rotación bonificando 1 unidad de alta rotación por cada 6 compradas. Meta mensual: Sunskin Oil Free 66, Capilplus Shampoo 134, Hydrafort Face 108, Capilplus Acondicionador 42 y Revival Crema 66 uds",
  "resumen": "Por cada 6 uds de una referencia de baja rotación el cliente recibe 1 bonificada de alta rotación (paga solo el IVA): Sunskin Oil Free → Sensibath; Capilplus Shampoo → Capilplus DS; Hydrafort Face → Hydrafort pH5; Capilplus Acondicionador → Capilplus DS; Revival → Sunskin SPF 50+ Emulsión. Aplica por múltiplos de 6 en cada pedido, también a clientes que ya tienen el portafolio codificado. El bonificado se carga solo en Odoo.",
  "obs": "Bonificado 6+1 cruzado. Los bonificados no suman en unidades vendidas",
  "pdf": "https://drive.google.com/file/d/1M4g933hHDbjYQh2vLg3psP0dq-G2pj6O/view",
  "productos": [
   {
    "c": "PT0005",
    "n": "Sunskin Oil Free x 80 g"
   },
   {
    "c": "PT0011",
    "n": "Capilplus Shampoo x 220 ml"
   },
   {
    "c": "PT0001",
    "n": "Hydrafort Face x 50 g"
   },
   {
    "c": "PT0014",
    "n": "Capilplus Acondicionador x 220 ml"
   },
   {
    "c": "PT0003",
    "n": "Revival Crema x 50 g"
   },
   {
    "c": "PT0012",
    "n": "Sensibath x 240 ml"
   },
   {
    "c": "PT0002",
    "n": "Capilplus DS Shampoo Anticaspa x 220 ml"
   },
   {
    "c": "PT0004",
    "n": "Hydrafort pH5 Ultrahumectante Crema x 250 g"
   },
   {
    "c": "PT0010",
    "n": "Sunskin SPF 50+ Emulsión x 80 g"
   }
  ],
  "canales": [
   "10",
   "11",
   "50",
   "51",
   "61",
   "70",
   "90"
  ],
  "clientes": [],
  "excluidos": [
   "Bella Piel S.A.S.",
   "Bella Piel S.A.S., Bella Piel Acomedica (AM)",
   "Bella Piel S.A.S., Bella Piel Bodega Distribucion (BDP)",
   "Bella Piel S.A.S., Bella Piel C.C Avenida Chile (AC)",
   "Bella Piel S.A.S., Bella Piel C.C Babilla Plaza (CB)",
   "Bella Piel S.A.S., Bella Piel C.C Buenavista (MN)",
   "Bella Piel S.A.S., Bella Piel C.C Caribe Plaza (CP)",
   "Bella Piel S.A.S., Bella Piel C.C Cañaveral (BC)",
   "Bella Piel S.A.S., Bella Piel C.C Cañaveral (BV)",
   "Bella Piel S.A.S., Bella Piel C.C Cedritos (CD)",
   "Bella Piel S.A.S., Bella Piel C.C Centro Suba (SU)",
   "Bella Piel S.A.S., Bella Piel C.C City Medica (MX)",
   "Bella Piel S.A.S., Bella Piel C.C Gran Plaza San Antonio (GT)",
   "Bella Piel S.A.S., Bella Piel C.C Gran Plaza Soacha (PG)",
   "Bella Piel S.A.S., Bella Piel C.C Gran Plaza el Sol (BS)",
   "Bella Piel S.A.S., Bella Piel C.C Granada Meta (ZG)",
   "Bella Piel S.A.S., Bella Piel C.C Jardin Plaza (JC)",
   "Bella Piel S.A.S., Bella Piel C.C La Casona Ph (CZ)",
   "Bella Piel S.A.S., Bella Piel C.C Los Caobos (LC)",
   "Bella Piel S.A.S., Bella Piel C.C Metropolis (ME)",
   "Bella Piel S.A.S., Bella Piel C.C Plaza Claro (PO)",
   "Bella Piel S.A.S., Bella Piel C.C Plaza Imperial 133 (IP)",
   "Bella Piel S.A.S., Bella Piel C.C Plaza de las Americas (AP)",
   "Bella Piel S.A.S., Bella Piel C.C Puerta del Norte (MH)",
   "Bella Piel S.A.S., Bella Piel C.C Salitre Plaza (PS)",
   "Bella Piel S.A.S., Bella Piel C.C San Diego 1485 (SD)",
   "Bella Piel S.A.S., Bella Piel C.C San Nicolas (MQ)",
   "Bella Piel S.A.S., Bella Piel C.C Santa Barbara (HB)",
   "Bella Piel S.A.S., Bella Piel C.C Santa Fe (SV)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Armenia (UA)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Cali 447 (UC)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Neiva (UN)",
   "Bella Piel S.A.S., Bella Piel C.C Unicentro Pasto (PU)",
   "Bella Piel S.A.S., Bella Piel C.C Ventura Cucuta (VC)",
   "Bella Piel S.A.S., Bella Piel C.C Viva Wajira (VG)",
   "Bella Piel S.A.S., Bella Piel C.C Viva la Ceja (AL)",
   "Bella Piel S.A.S., Bella Piel C.C. Andino (AN)",
   "Bella Piel S.A.S., Bella Piel C.C. Arkadia (MA)",
   "Bella Piel S.A.S., Bella Piel C.C. Avenida (AF)",
   "Bella Piel S.A.S., Bella Piel C.C. Buenavista (BU)",
   "Bella Piel S.A.S., Bella Piel C.C. Cafam Floresta (CF)",
   "Bella Piel S.A.S., Bella Piel C.C. Calima (CC)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Chia (CH)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Logistico (PW)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Mayor (CM)",
   "Bella Piel S.A.S., Bella Piel C.C. Centro Mayor (CN)",
   "Bella Piel S.A.S., Bella Piel C.C. Chipichape (CA)",
   "Bella Piel S.A.S., Bella Piel C.C. Cosmocentro (CO)",
   "Bella Piel S.A.S., Bella Piel C.C. Diver Plaza (DP)",
   "Bella Piel S.A.S., Bella Piel C.C. Ecoplaza (EC)",
   "Bella Piel S.A.S., Bella Piel C.C. Edificio Torre Palatino (EP)",
   "Bella Piel S.A.S., Bella Piel C.C. El Tesoro Parque Comercial (MT)",
   "Bella Piel S.A.S., Bella Piel C.C. Florida Parque Comercial (ML)",
   "Bella Piel S.A.S., Bella Piel C.C. Fontanar (FT)",
   "Bella Piel S.A.S., Bella Piel C.C. Fundadores (FM)",
   "Bella Piel S.A.S., Bella Piel C.C. Galerias (GA)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Estacion (GE)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Estacion (GN)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Plaza - La Libertad (FP)",
   "Bella Piel S.A.S., Bella Piel C.C. Gran Plaza Alcaravan (AY)",
   "Bella Piel S.A.S., Bella Piel C.C. Guatapuri (UV)",
   "Bella Piel S.A.S., Bella Piel C.C. Hacienda Santa Barbara (HN)",
   "Bella Piel S.A.S., Bella Piel C.C. Hacienda Santa Barbara (HS)",
   "Bella Piel S.A.S., Bella Piel C.C. Hayuelos (HY)",
   "Bella Piel S.A.S., Bella Piel C.C. Holguines Trade Center (CG)",
   "Bella Piel S.A.S., Bella Piel C.C. Innovo Plaza (DI)",
   "Bella Piel S.A.S., Bella Piel C.C. Jardin Plaza (CJ)",
   "Bella Piel S.A.S., Bella Piel C.C. La Estacion (EI)",
   "Bella Piel S.A.S., Bella Piel C.C. La Estacion (LI)",
   "Bella Piel S.A.S., Bella Piel C.C. La Mansion (BB)",
   "Bella Piel S.A.S., Bella Piel C.C. Mall Plaza (BM)",
   "Bella Piel S.A.S., Bella Piel C.C. Mall Plaza Buenavista (BA)",
   "Bella Piel S.A.S., Bella Piel C.C. Mayorca (MY)",
   "Bella Piel S.A.S., Bella Piel C.C. Mercurio (MB)",
   "Bella Piel S.A.S., Bella Piel C.C. Molinos (MM)",
   "Bella Piel S.A.S., Bella Piel C.C. Multicentro Ibague (MI)",
   "Bella Piel S.A.S., Bella Piel C.C. Multiplaza (MF)",
   "Bella Piel S.A.S., Bella Piel C.C. Nuestro Bogota (NB)",
   "Bella Piel S.A.S., Bella Piel C.C. Nuestro Cartago (NC)",
   "Bella Piel S.A.S., Bella Piel C.C. Palatino (PL)",
   "Bella Piel S.A.S., Bella Piel C.C. Parque Alegra (BL)",
   "Bella Piel S.A.S., Bella Piel C.C. Parque la Colina (CE)",
   "Bella Piel S.A.S., Bella Piel C.C. Paseo Villa del Rio (PR)",
   "Bella Piel S.A.S., Bella Piel C.C. Pereira Plaza (PP)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza Central (PC)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza De Las Americas (PZ)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza Imperial (PI)",
   "Bella Piel S.A.S., Bella Piel C.C. Plaza Mayor (BP)",
   "Bella Piel S.A.S., Bella Piel C.C. Portal 80 (PN)",
   "Bella Piel S.A.S., Bella Piel C.C. Portal Quindio (PQ)",
   "Bella Piel S.A.S., Bella Piel C.C. Premium Plaza (MP)",
   "Bella Piel S.A.S., Bella Piel C.C. Primavera Urbana (VP)",
   "Bella Piel S.A.S., Bella Piel C.C. Salitre Plaza (SA)",
   "Bella Piel S.A.S., Bella Piel C.C. San Diego (MD)",
   "Bella Piel S.A.S., Bella Piel C.C. San Pedro (NS)",
   "Bella Piel S.A.S., Bella Piel C.C. Santa Fe (SN)",
   "Bella Piel S.A.S., Bella Piel C.C. Santa Fe Jumbo (SP)",
   "Bella Piel S.A.S., Bella Piel C.C. Santa Lucia Plaza (BN)",
   "Bella Piel S.A.S., Bella Piel C.C. Santafe (MS)",
   "Bella Piel S.A.S., Bella Piel C.C. Suchiima (RS)",
   "Bella Piel S.A.S., Bella Piel C.C. Titan Plaza (TE)",
   "Bella Piel S.A.S., Bella Piel C.C. Titan Plaza (TN)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro (CU)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro (UE)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Girardot (UG)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Medellin (MU)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Occidente (UO)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Primer Piso (UP)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Tunja (UT)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Villavicencio (VU)",
   "Bella Piel S.A.S., Bella Piel C.C. Unicentro Yopal (UY)",
   "Bella Piel S.A.S., Bella Piel C.C. Ventura Terreros (TB)",
   "Bella Piel S.A.S., Bella Piel C.C. Viva Barranquilla (BI)",
   "Bella Piel S.A.S., Bella Piel C.C. Viva Tunja (VT)",
   "Bella Piel S.A.S., Bella Piel C.C. Viva Villavicencio (VB)",
   "Bella Piel S.A.S., Bella Piel CC. La Quinta (BQ)",
   "Bella Piel S.A.S., Bella Piel Campanario (LC)",
   "Bella Piel S.A.S., Bella Piel Castellana 98 Isla (LL)",
   "Bella Piel S.A.S., Bella Piel Centro Especialista Cl 90 (CS)",
   "Bella Piel S.A.S., Bella Piel Centro Internacional de Especialistas (BE)",
   "Bella Piel S.A.S., Bella Piel Centro Mayor (CR)",
   "Bella Piel S.A.S., Bella Piel Centro Medico Calle 91 (NO)",
   "Bella Piel S.A.S., Bella Piel Centro Medico de la Sabana (SB)",
   "Bella Piel S.A.S., Bella Piel Clinica Porto Azul (BJ)",
   "Bella Piel S.A.S., Bella Piel Colina 153 Isla (IC)",
   "Bella Piel S.A.S., Bella Piel Edificio Castellana 98 (LL)",
   "Bella Piel S.A.S., Bella Piel Edificio Colon Corporacion Medico Empresarial PH- Las Nieves (CT)",
   "Bella Piel S.A.S., Bella Piel Edificio Global Medical Center (GM)",
   "Bella Piel S.A.S., Bella Piel Edificio North West 94 (NW)",
   "Bella Piel S.A.S., Bella Piel Edificio Salud y Servicios PH (MR)",
   "Bella Piel S.A.S., Bella Piel Edificio San Sebastián del Country (SS)",
   "Bella Piel S.A.S., Bella Piel Edificio Santa Ana Medical Center (SM)",
   "Bella Piel S.A.S., Bella Piel Edificio Torres Zentai (TZ)",
   "Bella Piel S.A.S., Bella Piel El Country (ZC)",
   "Bella Piel S.A.S., Bella Piel Florida Parque Comercial (LM)",
   "Bella Piel S.A.S., Bella Piel Gradeco Business Plaza (EG)",
   "Bella Piel S.A.S., Bella Piel Hayuelos (HA)",
   "Bella Piel S.A.S., Bella Piel Hospital Universitario La Fundacion Santafe De Bogota (FS)",
   "Bella Piel S.A.S., Bella Piel Llanogrande Plaza (VL)",
   "Bella Piel S.A.S., Bella Piel Mall Plaza Cartagena (CX)",
   "Bella Piel S.A.S., Bella Piel Mall Plaza Manizales (PM)",
   "Bella Piel S.A.S., Bella Piel Micentro Funza PH (FZ)",
   "Bella Piel S.A.S., Bella Piel North West Isla (NW)",
   "Bella Piel S.A.S., Bella Piel Pacific Center (CK)",
   "Bella Piel S.A.S., Bella Piel Palmetto Plaza 134 (TC)",
   "Bella Piel S.A.S., Bella Piel Parque Comercial Guacarí Sincelejo (GS)",
   "Bella Piel S.A.S., Bella Piel Pasaje Astoria (MJ)",
   "Bella Piel S.A.S., Bella Piel Proyecto de Vida Centro Profesional PH (CV)",
   "Bella Piel S.A.S., Bella Piel S.A.S C.C Gran Estacion (GO)",
   "Bella Piel S.A.S., Bella Piel S.A.S C.C Mayorca (YM)",
   "Bella Piel S.A.S., Bella Piel S.A.S C.C Palatino (LP)",
   "Bella Piel S.A.S., Bella Piel S.A.S Centro Comercial Plaza Imperial(PE)",
   "Bella Piel S.A.S., Bella Piel S.A.S., Centro Logistico (DM)",
   "Bella Piel S.A.S., Bella Piel Sabana Park Health & Businees (SH)",
   "Bella Piel S.A.S., Bella Piel Salud Vegas Torre Medica PH (MV)",
   "Bella Piel S.A.S., Bella Piel San Nicolas 2369 (MW)",
   "Bella Piel S.A.S., Bella Piel Supercentro Tulua la 14 (TS)",
   "Bella Piel S.A.S., Bella Piel Zonata Centro Medico (ZO)",
   "Tienda Dermocosmetica Bella Piel, Juanita Ceron Delgado"
  ],
  "todos": false,
  "interna": false
 },
 {
  "c": "2026-034",
  "tipo": "Incentivo Fuerza de Ventas",
  "nombre": "Afilia y gana con Protocolo Medico",
  "grupo": "Todo portafolio",
  "dirigida": "Canales 20, 21, 22 (Protocolo Médico)",
  "producto": "Todo el portafolio",
  "ini": "2026-10-07",
  "fin": "2026-11-30",
  "objetivo": "Ampliar la cobertura del Protocolo Médico: captar médicos nuevos y reactivar los de la lista (clasificación 20, 21 y 22) para que más médicos formulen cada mes",
  "resumen": "Incentivo a la visitadora que cumpla la meta de su zona: Zona Norte y Zona Sur, 5 médicos activados o reactivados (mínimo 1 reactivado) y $249.551 cada una; Zona Desarrollo, 1 médico por activar y $100.000. Cuenta la formulación facturada de al menos $10.000 entre el 1 de septiembre y el 30 de noviembre de 2026. Se paga en diciembre con la liquidación del Protocolo Médico.",
  "obs": "Anexo 1: 9 médicos por reactivar. Anexo 2: 235 por activar. Anexo 3: 29 activos (no cuentan para la meta). Los anexos no vienen en el PDF. En Zona Sur el incentivo es para Yunelis Caballero. Incluye el Formulador del Año Revival (circular 2026-001)",
  "pdf": "",
  "productos": [],
  "canales": [
   "20",
   "21",
   "22"
  ],
  "clientes": [],
  "excluidos": [],
  "todos": false,
  "interna": false
 }
];
